---
title: "Energia RJ"
author: "Rodrigo"
date: "2025-01-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r PACOTES ,warning=FALSE,include=TRUE, message=FALSE}

library(tidyverse)
library(sf)
library(geobr)
library(plotly)
library(leaflet)
library(viridis)

```


```{r TEMPERATURA, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Dados Temperatura

temp = read.csv("C:/Users/rodri/OneDrive - Insper/ConsumoEnergiaRJ/Temperaturas - RJ/TODOS OS ANOS.CSV", 
              fileEncoding = 'Latin1', sep = ";")

# Renomear as colunas do dataset
names(temp) <- c(
  "data",
  "hora_utc",
  "precipitacao_mm",
  "pressao_estacao_mb",
  "pressao_max_mb",
  "pressao_min_mb",
  "radiacao_kj_m2",
  "temp_ar_c",
  "temp_orvalho_c",
  "temp_max_c",
  "temp_min_c",
  "temp_orvalho_max_c",
  "temp_orvalho_min_c",
  "umid_rel_max",
  "umid_rel_min",
  "umid_rel",
  "vento_direcao_graus",
  "vento_rajada_max_ms",
  "vento_vel_ms"
)

# Visualizar os novos nomes
str(temp)

```

```{r, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Definir as colunas que devem ser convertidas para o formato numérico, tratando NA
cols_to_numeric <- c(
  "precipitacao_mm",         # Precipitação em milímetros
  "pressao_estacao_mb",      # Pressão atmosférica na estação em milibares
  "pressao_max_mb",          # Pressão máxima em milibares
  "pressao_min_mb",          # Pressão mínima em milibares
  "radiacao_kj_m2",          # Radiação em kilojoules por metro quadrado
  "temp_ar_c",               # Temperatura do ar em graus Celsius
  "temp_orvalho_c",          # Temperatura do ponto de orvalho em graus Celsius
  "temp_max_c",              # Temperatura máxima em graus Celsius
  "temp_min_c",              # Temperatura mínima em graus Celsius
  "temp_orvalho_max_c",      # Temperatura máxima do ponto de orvalho em graus Celsius
  "temp_orvalho_min_c",      # Temperatura mínima do ponto de orvalho em graus Celsius
  "umid_rel_max",            # Umidade relativa máxima em porcentagem
  "umid_rel_min",            # Umidade relativa mínima em porcentagem
  "umid_rel",                # Umidade relativa média em porcentagem
  "vento_direcao_graus",     # Direção do vento em graus
  "vento_rajada_max_ms",     # Velocidade máxima de rajada de vento em metros por segundo
  "vento_vel_ms"             # Velocidade média do vento em metros por segundo
)

# Substituir vírgulas por pontos nos valores das colunas selecionadas e convertê-los para numérico
temp[cols_to_numeric] <- lapply(temp[cols_to_numeric], function(col) {
  as.numeric(gsub(",", ".", col)) # Substituir "," por "." e converter para numérico
})

# Agrupar os dados por data e calcular a média da temperatura máxima, ignorando valores NA
temp1 <- temp %>%
  group_by(data) %>%                            # Agrupar os dados por data
  summarise(temp_max_c = mean(temp_max_c, na.rm = TRUE)) %>%  # Calcular a média da temperatura máxima
  mutate(data = as.Date(data, format = "%d/%m/%Y")) %>%      # Converter a coluna 'data' para o formato de data
  arrange((data))                                            # Ordenar os dados pela data

# Criar um objeto com os 10 dias de maior temperatura máxima
top_10_dias_maior_temp <- temp1 %>%
  slice_max(temp_max_c, n = 10) # Selecionar os 10 maiores valores de temperatura máxima

top_10_dias_maior_temp # Visualizar o objeto com os 10 dias de maior temperatura máxima


```

```{r, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Criar um objeto com os 10 dias de menor temperatura máxima
top_10_dias_menor_temp <- temp1 %>%
  slice_min(temp_max_c, n = 10) # Selecionar os 10 menores valores de temperatura máxima

top_10_dias_menor_temp # Visualizar o objeto com os 10 dias de menor temperatura máxima


```

```{r, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Criando um gráfico interativo
plot_ly(
  data = temp1, 
  x = ~data, 
  y = ~temp_max_c, 
  type = 'scatter', 
  mode = 'lines',
  line = list(shape = 'linear', color = 'black', width = 0.5),  # Linha azul e espessura ajustada
  hoverinfo = 'text',
  text = ~paste('Data:', format(data, "%d/%m/%Y"), '<br>Temp Máxima (°C):', round(temp_max_c, 1))
) 


```

```{r, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Agrupamento por mês e cálculo da temperatura máxima média
temp1 <- temp %>%
  mutate(mes = format(as.Date(data, format = "%d/%m/%Y"), "%Y-%m")) %>%  # Extrair o mês e o ano da coluna 'data'
  group_by(mes) %>%                                                      # Agrupar os dados por mês
  summarise(temp_max_c = mean(temp_max_c, na.rm = TRUE)) %>%             # Calcular a média da temperatura máxima por mês
  mutate(mes = as.Date(paste0(mes, "-01"))) %>%                          # Converter o mês de volta para o formato de data (primeiro dia do mês)
  arrange(mes)                                                           # Ordenar os dados pelo mês

# Criar um objeto com os 10 meses de maior temperatura máxima média
top_10_mes_maior_temp <- temp1 %>%
  slice_max(temp_max_c, n = 10) # Selecionar os 10 maiores valores de temperatura máxima média por mês

top_10_mes_maior_temp # Visualizar o objeto com os 10 meses de maior temperatura máxima média


```

```{r, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Criar um objeto com os 10 meses de menor temperatura máxima média
top_10_mes_menor_temp <- temp1 %>%
  slice_min(temp_max_c, n = 10) # Selecionar os 10 menores valores de temperatura máxima média por mês

top_10_mes_menor_temp # Visualizar o objeto com os 10 meses de menor temperatura máxima média


```

```{r, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Criando o gráfico interativo por mês
plot_ly(
  data = temp1, 
  x = ~mes, 
  y = ~temp_max_c, 
  type = 'scatter', 
  mode = 'lines+markers',
  line = list(shape = 'linear', color = 'blue', width = 2),  # Linha azul e espessura ajustada
  marker = list(size = 6, color = 'red'),  # Marcadores vermelhos maiores
  hoverinfo = 'text',
  text = ~paste('Mês:', format(mes, "%b %Y"), '<br>Temp Máxima (°C):', round(temp_max_c, 1))
) %>%
  layout(
    title = 'Evolução da Temperatura Máxima Média Mensal',
    xaxis = list(
      title = 'Mês',
      tickformat = "%b %Y",  # Formato dos ticks no eixo X
      rangeslider = list(visible = TRUE)  # Adiciona slider para facilitar o zoom
    ),
    yaxis = list(title = 'Temperatura Máxima (°C)'),
    hovermode = 'x unified'  # Mostra valores em uma linha vertical ao passar o mouse
  )

```

```{r, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Análise de chuva

preciptacao <- temp %>%
  group_by(data) %>%                                                   # Agrupar os dados por data
  summarise(precipitacao_mm = mean(precipitacao_mm, na.rm = TRUE)) %>% # Calcular a média da precipitação (mm) por dia, ignorando valores NA
  mutate(data = as.Date(data, format = "%d/%m/%Y")) %>%                # Converter a coluna 'data' para o formato de data
  arrange((data))                                                      # Ordenar os dados por data em ordem crescente

# Criar um objeto com os 10 dias de maior precipitação média
top_10_dias_maior_chuva <- preciptacao %>%
  slice_max(precipitacao_mm, n = 10) # Selecionar os 10 maiores valores de precipitação média por dia

top_10_dias_maior_chuva # Visualizar o objeto com os 10 dias de maior precipitação média



```

```{r, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Criar um objeto com os 10 dias de menor precipitação média
top_10_dias_menor_chuva <- preciptacao %>%
  slice_min(precipitacao_mm, n = 10) # Selecionar os 10 menores valores de precipitação média por dia

top_10_dias_menor_chuva # Visualizar o objeto com os 10 dias de menor precipitação média

```

```{r, warning=FALSE, message=FALSE,cache.comments=FALSE,fig.keep='all'}

# Leitura dos dados de energia

energia <- read_sf("C:/Users/rodri/OneDrive - Insper/ConsumoEnergiaRJ/DadosCompletos.csv") # Carregar o arquivo CSV com os dados de energia

energia <- energia %>% 
  filter(BAIRRO != "RIO DE JANEIRO") # Filtrar os dados para excluir o bairro 'RIO DE JANEIRO'

energia$total_consumo_kwh <- as.numeric(energia$total_consumo_kwh) # Converter a coluna de consumo total de energia para numérico

# Converter MES_REFERENCIA para o formato de data
energia <- energia %>%
  mutate(MES_REFERENCIA = as.Date(MES_REFERENCIA, format = "%d/%m/%Y")) # Converter a coluna 'MES_REFERENCIA' para o formato de data

# Agrupar os dados por bairro e mês, somar o consumo total de energia
energia <- energia %>%
  group_by(BAIRRO, MES_REFERENCIA) %>%
  summarise(total_consumo_kwh = sum(total_consumo_kwh, na.rm = TRUE)) %>%  # Somar o consumo de energia por bairro e mês
  mutate(total_consumo_kwh = as.integer(total_consumo_kwh)) # Garantir que o consumo total seja tratado como inteiro

# Criar um gráfico interativo da série temporal de consumo de energia
plot_ly(data = energia, 
        x = ~MES_REFERENCIA, 
        y = ~total_consumo_kwh, 
        type = 'scatter', 
        mode = 'lines+markers', 
        color = ~BAIRRO,  # Diferenciar as linhas por bairro
        text = ~paste('Bairro:', BAIRRO, '<br>Total Consumption (kWh):', total_consumo_kwh, '<br>Month:', MES_REFERENCIA),
        hoverinfo = 'text',  # Esta linha garante que somente as informações de texto sejam mostradas no hover
        name = ~BAIRRO,
        line = list(shape = 'linear')) %>%
  layout(title = 'Monthly Energy Consumption Over Time', # Título do gráfico
         xaxis = list(title = 'Month'), # Título do eixo X
         yaxis = list(title = 'Total Consumption (kWh)'), # Título do eixo Y
         hovermode = 'closest') # Define o modo de hover para mostrar os dados do ponto mais próximo



```

```{r, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Resumo do consumo total de energia por bairro
energia_summary <- energia %>%
  group_by(BAIRRO) %>%
  summarise(total_consumo_kwh = sum(total_consumo_kwh, na.rm = TRUE)) %>%
  ungroup() # Resumo do consumo total de energia por bairro

# Criar um objeto com os 10 bairros de maior consumo de energia
top_10_bairros <- energia_summary %>%
  slice_max(total_consumo_kwh, n = 10) # Selecionar os 10 bairros com maior consumo de energia

# Criar um objeto com os 10 bairros de menor consumo de energia
bottom_10_bairros <- energia_summary %>%
  slice_min(total_consumo_kwh, n = 10) # Selecionar os 10 bairros com menor consumo de energia

# Visualizar os resultados
print(top_10_bairros) # Exibir os 10 bairros com maior consumo
print(bottom_10_bairros) # Exibir os 10 bairros com menor consumo


```

```{r, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Resumir o consumo total de energia por BAIRRO e MES_REFERENCIA
energia_summary <- energia %>%
  group_by(BAIRRO, MES_REFERENCIA) %>%  # Agrupar os dados por bairro e mês
  summarise(total_consumo_kwh = sum(total_consumo_kwh, na.rm = TRUE)) %>%  # Somar o consumo de energia, ignorando os valores ausentes (NA)
  ungroup()  # Remover o agrupamento após o cálculo da soma

# Criar um objeto com os 10 bairros de maior consumo de energia
top_10_bairros <- energia_summary %>%
  slice_max(total_consumo_kwh, n = 10)  # Selecionar os 10 bairros com maior consumo de energia

# Criar um objeto com os 10 bairros de menor consumo de energia
bottom_10_bairros <- energia_summary %>%
  slice_min(total_consumo_kwh, n = 10)  # Selecionar os 10 bairros com menor consumo de energia

# Visualizar os resultados
print(top_10_bairros)  # Exibir os 10 bairros com maior consumo de energia
print(bottom_10_bairros)  # Exibir os 10 bairros com menor consumo de energia

```


```{r}
rj = read_census_tract(code_tract = "RJ", year = 2010)

# Convert to uppercase and remove special characters
rj$name_neighborhood <- rj$name_neighborhood %>%
  toupper() %>%                          # Convert to uppercase
  str_replace_all("[^A-Z0-9 ]", "")    

```

```{r, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Carregar dados de renda por setor censitário
rj1 = read.csv("C:/Users/rodri/OneDrive - Insper/ConsumoEnergiaRJ/Dados/RJ_20231030/Base informaçoes setores2010 universo RJ/CSV/Basico_RJ.csv",
               sep = ";", fileEncoding = 'Latin1')  # Carregar arquivo CSV contendo os dados de renda por setor censitário

# Selecionar apenas as colunas necessárias
rj1 <- rj1 %>% 
  select(Cod_setor, V005)  # Selecionar as colunas Cod_setor (código do setor) e V005 (renda)

# Garantir que a coluna 'Cod_setor' seja do tipo caractere
rj1$Cod_setor = as.character(rj1$Cod_setor)

# Unir os dados de rj1 com outro dataframe rj usando a coluna 'Cod_setor' de rj1 e 'code_tract' de rj
rj2 <- merge(rj, rj1, by.y = "Cod_setor", by.x = "code_tract")  # Realizar a mesclagem dos dados

# Substituir vírgulas por pontos e converter para numérico a coluna 'V005'
rj2$V005 <- gsub(pattern = ",", replacement = ".", x = rj2$V005)  # Substituir vírgula por ponto decimal
rj2$V005 <- as.numeric(rj2$V005)  # Converter a coluna para tipo numérico

# Renomear a coluna 'V005' para 'Renda' e filtrar os dados para o município do Rio de Janeiro
rj2 <- rj2 %>% 
  rename(Renda=V005) %>%  # Renomear coluna para 'Renda'
  filter(name_muni == "Rio De Janeiro")  # Filtrar apenas os dados do município do Rio de Janeiro

summary(rj2$Renda)  # Exibir um resumo estatístico da variável 'Renda'


```



```{r, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Calcular os deciséis e criar categorias personalizadas para a renda
rj2 <- rj2 %>%
  filter(!is.na(Renda)) %>%  # Remover linhas onde 'Renda' é NA (valor ausente)
  mutate(
    Quintil = ntile(Renda, 5),  # Dividir a renda em 5 quintis (categorias baseadas nos percentis)
    Renda_Quint = case_when(  # Criar uma nova coluna com categorias de quintil
      Quintil == 1 ~ "0-20%",  # 1º quintil: 0-20%
      Quintil == 2 ~ "20-40%",  # 2º quintil: 20-40%
      Quintil == 3 ~ "40-60%",  # 3º quintil: 40-60%
      Quintil == 4 ~ "60-80%",  # 4º quintil: 60-80%
      Quintil == 5 ~ "80-100%",  # 5º quintil: 80-100%
    )
  )

# Carregar dados dos bairros do Rio de Janeiro
bairros_rj <- read_neighborhood(year = 2010, simplified = FALSE)  # Carregar os dados de bairros do Rio de Janeiro

# Filtrar e selecionar apenas bairros do município do Rio de Janeiro
bairros_rj <- bairros_rj %>% 
  filter(abbrev_state == "RJ") %>%  # Filtrar para o estado do Rio de Janeiro
  filter(name_muni == "Rio De Janeiro") %>%  # Filtrar para o município do Rio de Janeiro
  rename(Bairro = name_neighborhood) %>%  # Renomear a coluna de nome do bairro
  select(Bairro)  # Selecionar apenas a coluna com os nomes dos bairros



```

```{r, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Realizar o "join" espacial entre os dados de renda (rj2) e os bairros (bairros_rj)
rj3 <- st_join(x = rj2, y = bairros_rj)  # Realizar junção espacial, associando dados de renda aos bairros

# Transformar a projeção espacial para o sistema de coordenadas geográficas WGS84 (EPSG:4326)
rj3 <- st_transform(rj3, crs = 4326)  # Garantir que as coordenadas geográficas estejam no formato adequado (latitude e longitude)

# Criar paleta de cores customizada com base nos percentis de renda
breaks <- quantile(rj3$Renda, probs = seq(0, 1, by = 0.125), na.rm = TRUE)  # Calcular os percentis de 0 a 100% para a renda

pal <- colorBin(palette = "YlOrRd", domain = rj3$Renda, bins = breaks)  # Definir uma paleta de cores "YlOrRd" para representar a renda

# Criar mapa interativo com Leaflet
leaflet(data = rj3) %>%
  addTiles() %>%  # Adicionar o mapa base (tiles)
  addPolygons(
    fillColor = ~pal(Renda),  # Preencher as regiões com as cores definidas pela paleta, baseadas na renda
    fillOpacity = 0.9,  # Ajustar a opacidade do preenchimento das áreas
    color = "transparent",  # Remover a linha de borda das áreas (tornando-a transparente)
    weight = 0,  # Definir o peso da linha para 0, removendo a borda visível
    popup = ~paste("Bairro: ", Bairro, "Renda: ", Renda_Quint),  # Exibir informações sobre o bairro e o quintil da renda no popup
    label = ~paste("Bairro: ", Bairro, "Renda: ", Renda)  # Exibir rótulos com o nome do bairro e o valor da renda
  ) %>%
  addLegend(
    pal = pal,  # Adicionar a legenda com a paleta de cores para a renda
    values = rj3$Renda,  # Definir os valores a serem utilizados na legenda (renda)
    title = "Renda",  # Título da legenda
    opacity = 0.95  # Definir a opacidade da legenda
  ) %>%
  setView(lng = -43.1700, lat = -22.9068, zoom = 10)  # Ajustar a visualização do mapa para o Rio de Janeiro



```

```{r, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Agrupar dados por bairro e calcular a renda média e mediana por bairro
rj4 <- rj3 %>%
  st_drop_geometry() %>%  # Remover a geometria espacial (transformando em dados tabulares)
  group_by(Bairro) %>%  # Agrupar os dados pelo nome do bairro
  summarise(
    renda_media = mean(Renda, na.rm = TRUE),  # Calcular a renda média por bairro
    renda_mediana = median(Renda, na.rm = TRUE)  # Calcular a renda mediana por bairro
  )

# Realizar a junção dos dados de renda média com os bairros
bairros_rj2 <- merge(bairros_rj, rj4, by = "Bairro")  # Mesclar dados de renda média com os dados dos bairros

# Criar uma nova paleta de cores com base na renda média dos bairros
pal <- colorBin(palette = "YlOrRd", domain = bairros_rj2$renda_media, bins = 5)  # Definir a paleta de cores com 5 intervalos para a renda média

# Criar mapa interativo com Leaflet para visualizar a renda média por bairro
leaflet(data = bairros_rj2) %>%
  addTiles() %>%  # Adicionar o mapa base (tiles)
  addPolygons(
    fillColor = ~pal(renda_media),  # Preencher as áreas com as cores da paleta, baseadas na renda média
    fillOpacity = 0.9,  # Ajustar a opacidade do preenchimento das áreas
    color = "transparent",  # Remover a borda das áreas (tornando-a transparente)
    weight = 0,  # Definir o peso da borda para 0, removendo a linha visível
    popup = ~paste("Bairro: ", Bairro, "Renda Média: ", renda_media),  # Exibir a renda média de cada bairro no popup
    label = ~paste("Bairro: ", Bairro, "Renda Média: ", renda_media)  # Exibir a renda média nos rótulos dos bairros
  ) %>%
  addLegend(
    pal = pal,  # Adicionar a legenda com a paleta de cores para a renda média
    values = bairros_rj2$renda_media,  # Definir os valores a serem usados na legenda (renda média)
    title = "Renda Média",  # Título da legenda
    opacity = 0.7  # Definir a opacidade da legenda
  ) %>%
  setView(lng = -43.3900, lat = -22.9500, zoom = 10)  # Ajustar a visualização do mapa para o Rio de Janeiro


```

```{r, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Remover espaços extras e padronizar os nomes dos bairros para caixa alta nos dois datasets
energia_summary$BAIRRO <- trimws(toupper(energia_summary$BAIRRO))  # Remover espaços extras e converter para caixa alta
bairros_rj2$Bairro <- toupper(bairros_rj2$Bairro)  # Converter para caixa alta no segundo dataset

# Remover acentos da coluna Bairro em bairros_rj2 para padronização
bairros_rj2 <- bairros_rj2 %>%
  mutate(Bairro = iconv(Bairro, from = "UTF-8", to = "ASCII//TRANSLIT"))  # Remover acentos dos nomes dos bairros

# Ajustar alguns bairros específicos que têm nomes alternativos ou abreviados
bairros_rj2 <- bairros_rj2 %>%
  mutate(Bairro = ifelse(Bairro %in% c("FREGUESIA (ILHA DO GOVERNADOR)", "FREGUESIA (JACAREPAGUA)"), 
                         "FREGUESIA", Bairro)) %>%  # Agrupar bairros com variações no nome (Freguesia)
  group_by(Bairro) %>%  # Agrupar os dados pelo bairro
  summarise(
    renda_media = mean(renda_media, na.rm = TRUE),  # Calcular a média da renda por bairro
    renda_mediana = median(renda_mediana, na.rm = TRUE),  # Calcular a mediana da renda por bairro
    geom = st_union(geom)  # Unir os polígonos (necessário para manter a geometria na operação espacial)
  )

# Criar um dicionário de correção para os bairros
correcao_bairros <- c(
  "BENFICA " = "BENFICA",
  "CAJU " = "CAJU",
  "CATUMBI " = "CATUMBI",
  "CENTRO(RJ)" = "CENTRO",
  "CIDADE NOVA " = "CIDADE NOVA",
  "ESTACIO " = "ESTÁCIO",
  "FREGUESIA " = "FREGUESIA",
  "RIO COMPRIDO" = "RIO COMPRIDO",
  "MANGUEIRA" = "MANGUEIRA",
  "GAMBOA" = "GAMBOA",
  "SANTA TERESA" = "SANTA TERESA",
  "SANTO CRISTO" = "SANTO CRISTO",
  "SAO CRISTOVAO " = "SÃO CRISTÓVÃO",
  "SAUDE" = "SAUDE",
  "VASCO DA GAMA" = "VASCO DA GAMA"
)

# Aplicar as correções usando a função recode
energia_summary <- energia_summary %>%
  mutate(BAIRRO = recode(BAIRRO, !!!correcao_bairros)) %>%  # Corrigir os nomes dos bairros conforme o dicionário
  mutate(BAIRRO = iconv(BAIRRO, from = "UTF-8", to = "ASCII//TRANSLIT"))  # Remover acentos da coluna BAIRRO

# Verificar se existem bairros que não estão correspondendo entre os dois datasets
bairros_nao_correspondentes <- setdiff(energia_summary$BAIRRO, bairros_rj2$Bairro)  # Encontrar bairros não correspondentes

print(bairros_nao_correspondentes)  # Exibir os bairros que não coincidem entre os dois datasets



```

```{r, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Realizar a junção entre os datasets de energia e os bairros corrigidos
energia_bairros <- merge(bairros_rj2, energia_summary, by.x = "Bairro", by.y = "BAIRRO")  # Merge entre os datasets

# Filtrar os dados para remover o bairro "FREGUESIA", caso não seja relevante para a análise
energia_bairros <- energia_bairros %>% 
  filter(Bairro != "FREGUESIA")  # Filtrar para não incluir o bairro Freguesia

# Criar uma paleta de cores customizada com base nos percentis de consumo de energia
breaks <- quantile(energia_bairros$total_consumo_kwh, probs = seq(0, 1, by = 0.125), na.rm = TRUE)  # Calcular os percentis de consumo de energia
pal <- colorBin(palette = "Reds", domain = energia_bairros$total_consumo_kwh, bins = breaks)  # Definir a paleta de cores "Reds" para o consumo de energia

# Criar um mapa interativo com Leaflet para visualizar o consumo de energia por bairro
leaflet(data = energia_bairros) %>%
  addTiles() %>%  # Adicionar o mapa base (tiles)
  addPolygons(
    fillColor = ~pal(total_consumo_kwh),  # Preencher os bairros com cores baseadas no consumo de energia
    fillOpacity = 0.9,  # Ajustar a opacidade do preenchimento
    color = "transparent",  # Remover a borda dos polígonos
    weight = 0,  # Definir o peso da borda para 0, removendo a linha visível
    popup = ~paste("Bairro: ", Bairro, "total_consumo_kwh: ", total_consumo_kwh),  # Exibir o nome do bairro e o consumo de energia no popup
    label = ~paste("Bairro: ", Bairro, "total_consumo_kwh: ", total_consumo_kwh)  # Exibir o nome do bairro e o consumo de energia no rótulo
  ) %>%
  addLegend(
    pal = pal,  # Adicionar legenda com a paleta de cores
    values = energia_bairros$total_consumo_kwh,  # Definir os valores para a legenda
    title = "total_consumo_kwh",  # Título da legenda
    opacity = 0.5  # Ajustar a opacidade da legenda
  ) %>%
  setView(lng = -43.1650, lat = -22.9100, zoom = 12)  # Ajustar a visualização do mapa para o Rio de Janeiro



```

```{r, warning=FALSE, message=FALSE,cache.comments=FALSE, fig.keep='all'}

# Criar um gráfico com ggplot para mostrar o consumo de energia por bairro
ggplot() +
  geom_sf(data = energia_bairros, aes(fill = total_consumo_kwh), color = NA) +  # Plotar os bairros com o consumo de energia
  scale_fill_viridis_c() +  # Usar a paleta de cores "viridis" para o gráfico
  theme_void()  # Remover o fundo do gráfico


```

